/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.ArchivoCSV;
import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class VentanaParametros extends javax.swing.JFrame {

    public ArchivoCSV csv;
    public String infoEstudios[];
    public Boolean guardado;
    
    public VentanaParametros() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.csv = new ArchivoCSV();
        this.infoEstudios = csv.leerCSV();
        this.guardado = false;
        
        //TIEMPO
        duracionDia.setText(Integer.toString((Integer.parseInt(infoEstudios[0])/1000)));
        diasLanzamiento.setText(infoEstudios[1]);
        //DRIVE
        maxGuiones.setText(infoEstudios[2]);
        maxEscenarios.setText(infoEstudios[3]);
        maxAnimaciones.setText(infoEstudios[4]);
        maxDoblajes.setText(infoEstudios[5]);
        maxPlotTwits.setText(infoEstudios[6]);
        //PRODUCTORES CN
        numGuionistasCN.setText(infoEstudios[7]);
        numDisenadoresCN.setText(infoEstudios[8]);
        numAnimadoresCN.setText(infoEstudios[9]);
        numActoresCN.setText(infoEstudios[10]);
        numPlotTwistsCN.setText(infoEstudios[11]);
        numEnsambladoresCN.setText(infoEstudios[12]);
        //PRODUCTORES SC
        numGuionistasSC.setText(infoEstudios[13]);
        numDisenadoresSC.setText(infoEstudios[14]);
        numAnimadoresSC.setText(infoEstudios[15]);
        numActoresSC.setText(infoEstudios[16]);
        numPlotTwistsSC.setText(infoEstudios[17]);
        numEnsambladoresSC.setText(infoEstudios[18]);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        numAnimadoresSC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numActoresSC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        numEnsambladoresSC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        duracionDia = new javax.swing.JTextField();
        numGuionistasSC = new javax.swing.JTextField();
        diasLanzamiento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numDisenadoresSC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        irSimulacionButton = new javax.swing.JButton();
        irDashboardButton = new javax.swing.JButton();
        irParametrosButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        maxGuiones = new javax.swing.JTextField();
        maxEscenarios = new javax.swing.JTextField();
        maxAnimaciones = new javax.swing.JTextField();
        maxDoblajes = new javax.swing.JTextField();
        numEnsambladoresCN = new javax.swing.JTextField();
        numGuionistasCN = new javax.swing.JTextField();
        numDisenadoresCN = new javax.swing.JTextField();
        numAnimadoresCN = new javax.swing.JTextField();
        numActoresCN = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        maxPlotTwits = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        numPlotTwistsSC = new javax.swing.JTextField();
        numPlotTwistsCN = new javax.swing.JTextField();
        cambiarParam = new javax.swing.JToggleButton();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numAnimadoresSC.setBackground(new java.awt.Color(204, 204, 204));
        numAnimadoresSC.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        numAnimadoresSC.setForeground(new java.awt.Color(0, 0, 0));
        numAnimadoresSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numAnimadoresSC.setText("0");
        jPanel1.add(numAnimadoresSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, 40, 40));

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Animadores");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 210, 40));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Capacidad Diseñadores");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 170, 40));

        numActoresSC.setBackground(new java.awt.Color(204, 204, 204));
        numActoresSC.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        numActoresSC.setForeground(new java.awt.Color(0, 0, 0));
        numActoresSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numActoresSC.setText("0");
        jPanel1.add(numActoresSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 40, 40));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Actores");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 210, 40));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Capacidad Animadores");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 170, 40));

        numEnsambladoresSC.setBackground(new java.awt.Color(204, 204, 204));
        numEnsambladoresSC.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        numEnsambladoresSC.setForeground(new java.awt.Color(0, 0, 0));
        numEnsambladoresSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numEnsambladoresSC.setText("0");
        jPanel1.add(numEnsambladoresSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, 40, 40));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Duracion dia (seg)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 150, 50));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Capacidad Actores");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 180, 40));

        duracionDia.setBackground(new java.awt.Color(204, 204, 204));
        duracionDia.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        duracionDia.setForeground(new java.awt.Color(0, 0, 0));
        duracionDia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        duracionDia.setText("0");
        jPanel1.add(duracionDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 90, 50));

        numGuionistasSC.setBackground(new java.awt.Color(204, 204, 204));
        numGuionistasSC.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        numGuionistasSC.setForeground(new java.awt.Color(0, 0, 0));
        numGuionistasSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numGuionistasSC.setText("0");
        jPanel1.add(numGuionistasSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 40, 40));

        diasLanzamiento.setBackground(new java.awt.Color(204, 204, 204));
        diasLanzamiento.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        diasLanzamiento.setForeground(new java.awt.Color(0, 0, 0));
        diasLanzamiento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        diasLanzamiento.setText("0");
        jPanel1.add(diasLanzamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 90, 50));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Guionistas");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 210, 40));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Dias lanzamiento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 150, 50));

        numDisenadoresSC.setBackground(new java.awt.Color(204, 204, 204));
        numDisenadoresSC.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        numDisenadoresSC.setForeground(new java.awt.Color(0, 0, 0));
        numDisenadoresSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numDisenadoresSC.setText("0");
        jPanel1.add(numDisenadoresSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 40, 40));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Diseñadores");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 210, 40));

        jPanel3.setBackground(new java.awt.Color(51, 0, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        irSimulacionButton.setBackground(new java.awt.Color(0, 0, 0));
        irSimulacionButton.setFont(new java.awt.Font("NSimSun", 0, 14)); // NOI18N
        irSimulacionButton.setForeground(new java.awt.Color(204, 204, 204));
        irSimulacionButton.setText("Simulacion");
        irSimulacionButton.setBorder(null);
        irSimulacionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        irSimulacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irSimulacionButtonActionPerformed(evt);
            }
        });
        jPanel3.add(irSimulacionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 40, 130, 40));

        irDashboardButton.setBackground(new java.awt.Color(0, 0, 0));
        irDashboardButton.setFont(new java.awt.Font("NSimSun", 0, 14)); // NOI18N
        irDashboardButton.setForeground(new java.awt.Color(204, 204, 204));
        irDashboardButton.setText("Dashboard");
        irDashboardButton.setBorder(null);
        irDashboardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        irDashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irDashboardButtonActionPerformed(evt);
            }
        });
        jPanel3.add(irDashboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 90, 130, 40));

        irParametrosButton.setBackground(new java.awt.Color(0, 0, 0));
        irParametrosButton.setFont(new java.awt.Font("NSimSun", 0, 14)); // NOI18N
        irParametrosButton.setForeground(new java.awt.Color(204, 204, 204));
        irParametrosButton.setText("Parametros");
        irParametrosButton.setBorder(null);
        irParametrosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        irParametrosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irParametrosButtonActionPerformed(evt);
            }
        });
        jPanel3.add(irParametrosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 140, 130, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 110, 510));

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ESTUDIOS");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        jLabel13.setFont(new java.awt.Font("Poor Richard", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("PARAMETROS");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 770, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 770, 10));

        maxGuiones.setBackground(new java.awt.Color(204, 204, 204));
        maxGuiones.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        maxGuiones.setForeground(new java.awt.Color(0, 0, 0));
        maxGuiones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxGuiones.setText("0");
        jPanel1.add(maxGuiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 90, 40));

        maxEscenarios.setBackground(new java.awt.Color(204, 204, 204));
        maxEscenarios.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        maxEscenarios.setForeground(new java.awt.Color(0, 0, 0));
        maxEscenarios.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxEscenarios.setText("0");
        jPanel1.add(maxEscenarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 90, 40));

        maxAnimaciones.setBackground(new java.awt.Color(204, 204, 204));
        maxAnimaciones.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        maxAnimaciones.setForeground(new java.awt.Color(0, 0, 0));
        maxAnimaciones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxAnimaciones.setText("0");
        jPanel1.add(maxAnimaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 90, 40));

        maxDoblajes.setBackground(new java.awt.Color(204, 204, 204));
        maxDoblajes.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        maxDoblajes.setForeground(new java.awt.Color(0, 0, 0));
        maxDoblajes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxDoblajes.setText("0");
        jPanel1.add(maxDoblajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 90, 40));

        numEnsambladoresCN.setBackground(new java.awt.Color(204, 204, 204));
        numEnsambladoresCN.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        numEnsambladoresCN.setForeground(new java.awt.Color(0, 0, 0));
        numEnsambladoresCN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numEnsambladoresCN.setText("0");
        jPanel1.add(numEnsambladoresCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, 40, 40));

        numGuionistasCN.setBackground(new java.awt.Color(204, 204, 204));
        numGuionistasCN.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        numGuionistasCN.setForeground(new java.awt.Color(0, 0, 0));
        numGuionistasCN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numGuionistasCN.setText("0");
        jPanel1.add(numGuionistasCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 40, 40));

        numDisenadoresCN.setBackground(new java.awt.Color(204, 204, 204));
        numDisenadoresCN.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        numDisenadoresCN.setForeground(new java.awt.Color(0, 0, 0));
        numDisenadoresCN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numDisenadoresCN.setText("0");
        jPanel1.add(numDisenadoresCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 40, 40));

        numAnimadoresCN.setBackground(new java.awt.Color(204, 204, 204));
        numAnimadoresCN.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        numAnimadoresCN.setForeground(new java.awt.Color(0, 0, 0));
        numAnimadoresCN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numAnimadoresCN.setText("0");
        jPanel1.add(numAnimadoresCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 40, 40));

        numActoresCN.setBackground(new java.awt.Color(204, 204, 204));
        numActoresCN.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        numActoresCN.setForeground(new java.awt.Color(0, 0, 0));
        numActoresCN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numActoresCN.setText("0");
        jPanel1.add(numActoresCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 40, 40));

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Ensambladores");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 150, 40));

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Estudios");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 90, 30));

        jLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jLabel17.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("SC");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, 40, 30));

        jLabel18.setBackground(new java.awt.Color(204, 204, 204));
        jLabel18.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Capacidad Guionistas");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 170, 40));

        jLabel20.setBackground(new java.awt.Color(204, 204, 204));
        jLabel20.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("CN");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 40, 30));

        jLabel21.setBackground(new java.awt.Color(204, 204, 204));
        jLabel21.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Capacidad Plot Twist");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 180, 40));

        maxPlotTwits.setBackground(new java.awt.Color(204, 204, 204));
        maxPlotTwits.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        maxPlotTwits.setForeground(new java.awt.Color(0, 0, 0));
        maxPlotTwits.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxPlotTwits.setText("0");
        jPanel1.add(maxPlotTwits, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 90, 40));

        jLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jLabel22.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Plot Twist");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 210, 40));

        numPlotTwistsSC.setBackground(new java.awt.Color(204, 204, 204));
        numPlotTwistsSC.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        numPlotTwistsSC.setForeground(new java.awt.Color(0, 0, 0));
        numPlotTwistsSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numPlotTwistsSC.setText("0");
        jPanel1.add(numPlotTwistsSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, 40, 40));

        numPlotTwistsCN.setBackground(new java.awt.Color(204, 204, 204));
        numPlotTwistsCN.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        numPlotTwistsCN.setForeground(new java.awt.Color(0, 0, 0));
        numPlotTwistsCN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numPlotTwistsCN.setText("0");
        jPanel1.add(numPlotTwistsCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 40, 40));

        cambiarParam.setBackground(new java.awt.Color(51, 51, 51));
        cambiarParam.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        cambiarParam.setForeground(new java.awt.Color(255, 255, 255));
        cambiarParam.setText("Cambiar parametros");
        cambiarParam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarParamActionPerformed(evt);
            }
        });
        jPanel1.add(cambiarParam, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, 290, 50));

        jLabel19.setBackground(new java.awt.Color(204, 204, 204));
        jLabel19.setFont(new java.awt.Font("NSimSun", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Trabajadores");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 200, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void irSimulacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irSimulacionButtonActionPerformed
        this.dispose();
        VentanaSimulacion simulacion = new VentanaSimulacion();
        simulacion.setVisible(true);
    }//GEN-LAST:event_irSimulacionButtonActionPerformed

    private void irDashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irDashboardButtonActionPerformed
        this.dispose();
        VentanaDashboard dashboard = new VentanaDashboard();
        dashboard.setVisible(true);
    }//GEN-LAST:event_irDashboardButtonActionPerformed

    private void irParametrosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irParametrosButtonActionPerformed
        this.setEnabled(false);
    }//GEN-LAST:event_irParametrosButtonActionPerformed

    private void cambiarParamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarParamActionPerformed
        
        try {
            //Para la validacion de que sea solo entero el valor
            //ingresado en las casillas
            int numero;
            numero = Integer.parseInt(Integer.toString(Integer.parseInt(duracionDia.getText())*1000));
            numero = Integer.parseInt(diasLanzamiento.getText());
            
            numero = Integer.parseInt(maxGuiones.getText());
            numero = Integer.parseInt(maxEscenarios.getText());
            numero = Integer.parseInt(maxAnimaciones.getText());
            numero = Integer.parseInt(maxDoblajes.getText());
            numero = Integer.parseInt(maxPlotTwits.getText());
 
            numero = Integer.parseInt(numGuionistasCN.getText());
            numero = Integer.parseInt(numDisenadoresCN.getText());
            numero = Integer.parseInt(numAnimadoresCN.getText());
            numero = Integer.parseInt(numActoresCN.getText());
            numero = Integer.parseInt(numPlotTwistsCN.getText());
            numero = Integer.parseInt(numEnsambladoresCN.getText());
        
            numero = Integer.parseInt(numGuionistasSC.getText());
            numero = Integer.parseInt(numDisenadoresSC.getText());
            numero = Integer.parseInt(numAnimadoresSC.getText());
            numero = Integer.parseInt(numActoresSC.getText());
            numero = Integer.parseInt(numPlotTwistsSC.getText());
            numero = Integer.parseInt(numEnsambladoresSC.getText());
            
            infoEstudios[0] = Integer.toString(Integer.parseInt(duracionDia.getText())*1000);
            infoEstudios[1] = diasLanzamiento.getText();
        
            infoEstudios[2] = maxGuiones.getText();
            infoEstudios[3] = maxEscenarios.getText();
            infoEstudios[4] = maxAnimaciones.getText();
            infoEstudios[5] = maxDoblajes.getText();
            infoEstudios[6] = maxPlotTwits.getText();
        
            infoEstudios[7] = numGuionistasCN.getText();
            infoEstudios[8] = numDisenadoresCN.getText();
            infoEstudios[9] = numAnimadoresCN.getText();
            infoEstudios[10] = numActoresCN.getText();
            infoEstudios[11] = numPlotTwistsCN.getText();
            infoEstudios[12] = numEnsambladoresCN.getText();
        
            infoEstudios[13] = numGuionistasSC.getText();
            infoEstudios[14] = numDisenadoresSC.getText();
            infoEstudios[15] = numAnimadoresSC.getText();
            infoEstudios[16] = numActoresSC.getText();
            infoEstudios[17] = numPlotTwistsSC.getText();
            infoEstudios[18] = numEnsambladoresSC.getText();
        
            csv.GuardarCSV(infoEstudios[0], infoEstudios[1], 
                    infoEstudios[2], infoEstudios[3], infoEstudios[4], infoEstudios[5], infoEstudios[6], 
                    infoEstudios[7], infoEstudios[8], infoEstudios[9], infoEstudios[10], infoEstudios[11], infoEstudios[12], 
                    infoEstudios[13], infoEstudios[14], infoEstudios[15], infoEstudios[16], infoEstudios[17], infoEstudios[18]);
            JOptionPane.showMessageDialog(null,"Informacion de los estudios guardada");
            guardado = true;
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"ERROR, En las casillas solo deben ir números enteros");
            return;
        }
        
        

        
        
    }//GEN-LAST:event_cambiarParamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaParametros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton cambiarParam;
    private javax.swing.JTextField diasLanzamiento;
    private javax.swing.JTextField duracionDia;
    private javax.swing.JButton irDashboardButton;
    private javax.swing.JButton irParametrosButton;
    private javax.swing.JButton irSimulacionButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField maxAnimaciones;
    private javax.swing.JTextField maxDoblajes;
    private javax.swing.JTextField maxEscenarios;
    private javax.swing.JTextField maxGuiones;
    private javax.swing.JTextField maxPlotTwits;
    private javax.swing.JTextField numActoresCN;
    private javax.swing.JTextField numActoresSC;
    private javax.swing.JTextField numAnimadoresCN;
    private javax.swing.JTextField numAnimadoresSC;
    private javax.swing.JTextField numDisenadoresCN;
    private javax.swing.JTextField numDisenadoresSC;
    private javax.swing.JTextField numEnsambladoresCN;
    private javax.swing.JTextField numEnsambladoresSC;
    private javax.swing.JTextField numGuionistasCN;
    private javax.swing.JTextField numGuionistasSC;
    private javax.swing.JTextField numPlotTwistsCN;
    private javax.swing.JTextField numPlotTwistsSC;
    // End of variables declaration//GEN-END:variables
}
