/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author sebas
 */
public class VentanaDashboard extends javax.swing.JFrame {

    /**
     * Creates new form VentanaDashboard
     */
    public VentanaDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        irSimulacionButton = new javax.swing.JButton();
        irDashboardButton = new javax.swing.JButton();
        irParametrosButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        grafica1 = new javax.swing.JPanel();
        mensajeG1 = new javax.swing.JLabel();
        grafica2 = new javax.swing.JPanel();
        mensajeG2 = new javax.swing.JLabel();
        grafica3 = new javax.swing.JPanel();
        mensajeG3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ESTUDIOS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        jPanel3.setBackground(new java.awt.Color(52, 0, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        irSimulacionButton.setBackground(new java.awt.Color(0, 0, 0));
        irSimulacionButton.setFont(new java.awt.Font("NSimSun", 0, 14)); // NOI18N
        irSimulacionButton.setForeground(new java.awt.Color(204, 204, 204));
        irSimulacionButton.setText("Simulacion");
        irSimulacionButton.setBorder(null);
        irSimulacionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        irSimulacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irSimulacionButtonActionPerformed(evt);
            }
        });
        jPanel3.add(irSimulacionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 40, 130, 40));

        irDashboardButton.setBackground(new java.awt.Color(0, 0, 0));
        irDashboardButton.setFont(new java.awt.Font("NSimSun", 0, 14)); // NOI18N
        irDashboardButton.setForeground(new java.awt.Color(204, 204, 204));
        irDashboardButton.setText("Dashboard");
        irDashboardButton.setBorder(null);
        irDashboardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        irDashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irDashboardButtonActionPerformed(evt);
            }
        });
        jPanel3.add(irDashboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 90, 130, 40));

        irParametrosButton.setBackground(new java.awt.Color(0, 0, 0));
        irParametrosButton.setFont(new java.awt.Font("NSimSun", 0, 14)); // NOI18N
        irParametrosButton.setForeground(new java.awt.Color(204, 204, 204));
        irParametrosButton.setText("Parametros");
        irParametrosButton.setBorder(null);
        irParametrosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        irParametrosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irParametrosButtonActionPerformed(evt);
            }
        });
        jPanel3.add(irParametrosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 140, 130, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 110, 520));

        jLabel1.setFont(new java.awt.Font("Poor Richard", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("DASHBOARD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 770, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 770, 10));

        grafica1.setPreferredSize(new java.awt.Dimension(400, 200));
        grafica1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mensajeG1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grafica1.add(mensajeG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 450));

        jPanel1.add(grafica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 230, 450));

        grafica2.setPreferredSize(new java.awt.Dimension(400, 200));
        grafica2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        grafica2.add(mensajeG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 450));

        jPanel1.add(grafica2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 230, 450));

        grafica3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mensajeG3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grafica3.add(mensajeG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 450));

        jPanel1.add(grafica3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 230, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void irSimulacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irSimulacionButtonActionPerformed
        this.dispose();
        VentanaSimulacion simulacion = new VentanaSimulacion();
        simulacion.setVisible(true);
    }//GEN-LAST:event_irSimulacionButtonActionPerformed

    private void irDashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irDashboardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irDashboardButtonActionPerformed

    private void irParametrosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irParametrosButtonActionPerformed
        this.dispose();
        VentanaParametros parametros = new VentanaParametros();
        parametros.setVisible(true);
    }//GEN-LAST:event_irParametrosButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel grafica1;
    private javax.swing.JPanel grafica2;
    private javax.swing.JPanel grafica3;
    private javax.swing.JButton irDashboardButton;
    private javax.swing.JButton irParametrosButton;
    private javax.swing.JButton irSimulacionButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel mensajeG1;
    private javax.swing.JLabel mensajeG2;
    private javax.swing.JLabel mensajeG3;
    // End of variables declaration//GEN-END:variables
}
